import { Controller, Get, Param, ParseUUIDPipe, Post, UseGuards } from '@nestjs/common';
import { type ClinicalReminder, Role } from '@adoptafacil/contracts';
import type { RequestUser } from '../../core/auth/auth.types';
import { CurrentUser } from '../../core/auth/current-user.decorator';
import { JwtAuthGuard } from '../../core/auth/jwt-auth.guard';
import { Roles } from '../../core/rbac/roles.decorator';
import { RolesGuard } from '../../core/rbac/roles.guard';
import { RemindersService } from './reminders.service';

/** Roles that may VIEW reminders (§13 M03 — same set that sees the animal). */
const VIEW_ROLES = [
  Role.Owner,
  Role.Administrator,
  Role.Operator,
  Role.Veterinarian,
  Role.ReadOnlyAuditor,
] as const;

/** Roles that may RESOLVE (acknowledge/dismiss) — not the read-only auditor. */
const RESOLVE_ROLES = [Role.Owner, Role.Administrator, Role.Operator, Role.Veterinarian] as const;

/**
 * M03 clinical reminders inbox (RF09) — tenant-scoped (RLS). The reminders are
 * generated by the background worker; this exposes the in-app inbox. Viewing is
 * open to the animal-facing roles + the read-only auditor; acknowledging/
 * dismissing excludes the auditor (deny-by-default). Mounted at a distinct top
 * path so it never collides with `/animals/:id`.
 */
@Controller('clinical-reminders')
@UseGuards(JwtAuthGuard, RolesGuard)
export class RemindersController {
  constructor(private readonly service: RemindersService) {}

  @Get()
  @Roles(...VIEW_ROLES)
  list(): Promise<ClinicalReminder[]> {
    return this.service.list();
  }

  @Post(':id/acknowledge')
  @Roles(...RESOLVE_ROLES)
  acknowledge(
    @CurrentUser() actor: RequestUser,
    @Param('id', ParseUUIDPipe) id: string,
  ): Promise<ClinicalReminder> {
    return this.service.resolve(actor.id, id, 'acknowledge');
  }

  @Post(':id/dismiss')
  @Roles(...RESOLVE_ROLES)
  dismiss(
    @CurrentUser() actor: RequestUser,
    @Param('id', ParseUUIDPipe) id: string,
  ): Promise<ClinicalReminder> {
    return this.service.resolve(actor.id, id, 'dismiss');
  }
}
