-- ============================================================================
-- CANONICAL RLS REFERENCE (RNF03) — appended to the initial Prisma migration.
--
-- This SQL is NOT auto-generated by Prisma (Prisma does not model RLS). During
-- bootstrap it is appended to prisma/migrations/<ts>_init/migration.sql right
-- after the CREATE TABLE statements, then applied with `prisma migrate dev`.
--
-- Why a dedicated role: PostgreSQL SUPERUSERS bypass RLS entirely, and table
-- OWNERS bypass it unless FORCE is set. The app therefore connects as a
-- NON-SUPERUSER role (adoptafacil_app) and every tenant table uses FORCE.
-- ============================================================================

-- 1. Enable + FORCE Row-Level Security on the reference table.
ALTER TABLE "_rls_probe" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_rls_probe" FORCE ROW LEVEL SECURITY;

-- 2. Tenant isolation policy. A row is visible/insertable only when its
--    organization_id equals app.current_org_id set for the current transaction.
--    current_setting(..., true) returns NULL when unset => zero rows visible.
CREATE POLICY tenant_isolation ON "_rls_probe"
  USING ("organization_id" = current_setting('app.current_org_id', true)::uuid)
  WITH CHECK ("organization_id" = current_setting('app.current_org_id', true)::uuid);

-- 3. Application role (idempotent). NOSUPERUSER + NOBYPASSRLS so RLS applies.
--    Password is a non-secret local/CI dev value; production provisions its own.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'adoptafacil_app') THEN
    CREATE ROLE adoptafacil_app LOGIN PASSWORD 'adoptafacil_app' NOSUPERUSER NOBYPASSRLS;
  END IF;
END
$$;

-- 4. Least-privilege grants for the app role.
GRANT USAGE ON SCHEMA public TO adoptafacil_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON "organizations" TO adoptafacil_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON "_rls_probe" TO adoptafacil_app;

-- How the request sets the tenant (implemented fully by @sebastian in Ola 0):
--   BEGIN;
--   SELECT set_config('app.current_org_id', '<org-uuid>', true); -- txn-local
--   ... queries scoped to that org ...
--   COMMIT;
-- See PrismaService.withOrgContext() for the reference implementation.
